# syntax=docker/dockerfile:1
FROM python:3.8
ENV PYTHONUNBUFFERED=1

ARG GIT_ID
ARG GIT_PASSWORD
ARG GIT_USERNAME
ARG GIT_EMAIL

# install ssh
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y openssh-server

# install vim
RUN apt-get install -y vim

# install src

WORKDIR /home
RUN git clone http://$GIT_ID:$GIT_PASSWORD@github.com/greenrain78/OpenADR-backend.git
RUN git config --global user.name "$GIT_USERNAME"
RUN git config --global user.email "$GIT_EMAIL"

WORKDIR /home/OpenADR-backend
RUN python -m pip install -r /home/OpenADR-backend/requirements.txt

ENTRYPOINT ["sh", "/home/OpenADR-backend/entrypoint.sh" ]